[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "cython>=3.0",
    "numpy>=1.22"
]
build-backend = "setuptools.build_meta"

[project]
name = "aribrain"
version = "0.1.0"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]